using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Infocomm;

[Virtual]
[GenerateTypedNameReferences]
public partial class InfocommConsole : FancyWindow
{
    public InfocommConsole()
    {
        RobustXamlLoader.Load(this);
        
        StationName.AddStyleClass("LabelBig");
    }

   /* protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.Move;
    }*/
}
